version: '3'
services:
  server:
    image: node:latest
    working_dir: '/code'
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./server
        target: /code
    command: 'bash -c "npm install && npm run dev"'
    environment:
      - PGUSER=max
      - PGHOST=db
      - PGPASSWORD=secretpassword
      - PGDATABASE=kanban
      - PGPORT=5432
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - 'postgresdata:/var/lib/postgresql/data'
      - './db:/docker-entrypoint-initdb.d/:ro'
    environment:
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_USER=max
      - POSTGRES_DB=kanban
volumes:
  postgresdata:
