services:
  server:
    container_name: kanban_dev_api
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=development
    command: bash -c "npm install && npm run dev"
  db:
    container_name: kanban_dev_db
    volumes:
      - 'postgresdata:/var/lib/postgresql/data'
      - './db:/docker-entrypoint-initdb.d/:ro'
volumes:
  postgresdata:
networks:
  default:
    name: kanban_dev
