version: '3'
services:
  server:
    image: node:latest
    working_dir: '/code'
    volumes:
      - type: bind
        source: ./server
        target: /code
    depends_on:
      - db
    environment:
      - PGUSER=max
      - PGHOST=db
      - PGPASSWORD=secretpassword
      - PGDATABASE=kanban
      - PGPORT=5432
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_USER=max
      - POSTGRES_DB=kanban
    volumes:
      - './db:/docker-entrypoint-initdb.d/:ro'
